apiVersion: v1
kind: Namespace
metadata:
  name: code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: code
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: code
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  namespace: code
  name: app
  labels:
    app: app
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRRFVISHIyUHRuSU1EQU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdGwKZUdGdGNHeGxMbU52YlRBZUZ3MHlNREEyTURZeE56VTRORFZhRncwek1EQTJNRFF4TnpVNE5EVmFNQll4RkRBUwpCZ05WQkFNTUMyVjRZVzF3YkdVdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFwdUpUZHdtZE5lWTJhc3FKdG4ydTg1N2pWRWhMK2RzU1NhbnQ1Vys5ejFkdFcyeHJxamd1OVg4UDRUOWUKakdHbFo3cUt4RDM3YnlDQ21CT0xzZEU0Vis2d3ZnUjZFODdLNmpRL25mKzZDZmRPQUZ1V1dWVnFUN2UydGc2ZApGbFJMMDNLSi9IcUxjVVZiM3IwRVFvNkpFYnBiSDJYQ1lscHFvQ3RGeHRVVU1RZXc2M2JZeU81Y1YxWUdxQWwrCktZM21OMFRFRDZRR0JiMTRIdGhFbkMrcmZxN0VUdlJRQyswQlBQa2xHS1FBN0lkejZsY1VIZHQxbGlrNXVKSzkKSXpFTHEyTnpYLzRQZ2VWdnNwNGpvZVVCQ08yRU1GNFRtTkJsS1dKQm14M01CRzQ3eStqLzJIOWZsS0VYNXdURwpqZ3krS0R5U3NUbGdaTEZMdlRoenh3Rkp4UUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZ3L0QzCi84OU1PcUNSQ0ZSUXlEeGlDd2tPUVN5czQ0bmQ1T2NxRGhRRGtzaFZxZ28yZk5mNnZobkxRQndqS2NTbm1HamIKcXM0Nzl1YkVBSVU5ZmZtR0JUYXd6UEEwMjJna1J6WklTRjRrQVd1L2dvUlAxZ2J1S0ZuSUk4MUcwaGdXNzJZdQpvRVM2SnU0L1NzZmovYUQyZEFITzluaXp3Wk9OMC9ic0FZcyszUi9ZYSttTGkxc0xFdW5zV1dMSEpBTEd1Vyt2Cml6VFc3STJ5N0krNmxUUEZoc3J4QlV5OElIcUtzWmVNdmlIMGJqSTdBMHVTVkp3eG03ZVFYQW5yTkhKRWpnNnEKNFBlV2VsWUxPOFNWdzh5T1c2UUlKS3BLWDNpZzFBM2oyZjAvRDBTQm5uczVpYkF3UEovS1BtY0pwc1ZhWmpzegpROXo1SGhVWjJWb0pDYzV2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ200bE4zQ1owMTVqWnEKeW9tMmZhN3pudU5VU0V2NTJ4SkpxZTNsYjczUFYyMWJiR3VxT0M3MWZ3L2hQMTZNWWFWbnVvckVQZnR2SUlLWQpFNHV4MFRoWDdyQytCSG9UenNycU5EK2QvN29KOTA0QVc1WlpWV3BQdDdhMkRwMFdWRXZUY29uOGVvdHhSVnZlCnZRUkNqb2tSdWxzZlpjSmlXbXFnSzBYRzFSUXhCN0RyZHRqSTdseFhWZ2FvQ1g0cGplWTNSTVFQcEFZRnZYZ2UKMkVTY0w2dCtyc1JPOUZBTDdRRTgrU1VZcEFEc2gzUHFWeFFkMjNXV0tUbTRrcjBqTVF1clkzTmYvZytCNVcreQpuaU9oNVFFSTdZUXdYaE9ZMEdVcFlrR2JIY3dFYmp2TDZQL1lmMStVb1JmbkJNYU9ETDRvUEpLeE9XQmtzVXU5Ck9IUEhBVW5GQWdNQkFBRUNnZ0VBUVBCRkJrY3BjN1hYYXdyUk44QUVlaXhUelpJc2JsZCs4RWM5bVZBNERoeTUKSXlBM2JROWJ4by9oQUFlR3BSM0NIWEVMV24yNy8yd3BKVUJGMWJYU05QVmV0VEpNeHJSclpXTmJkZ0h5eExvRgpFa0tSYU1YQ0RxOHdXL3VueU82WWF2bGhGR3dqSXJxWW16MzJFR2dpa2xGdjcvSExDRGFpMHh6RGxER0tIK0Y3Clp4cElPSXNkeWM4bzg1T0xGZGNIMGxVOStsL3gwOTNJVG4rb1MrQko2dm0yTngzdHpOaTZHWkZJTUJjTXpWZlMKbTRoZVZZLzAvMzhFUUJObk5UUUdrSkkxMnlXNEErN0VuWFBSN1FGR3d6TG43S0kxNWNvY0FtKy9oZGIrc0c1TQptZEdCNlNOSlJsbWpPWU1JOFluTyszeVFyTzdCdngyYXRLY1FnT0QzYVFLQmdRRFIvYWJ2ekZKTFB4dGVmSUFlCnAzaWtZTi9Lem5CaWtKcWZWUS9mNlAvaGszYWZBWCt6MFpMNEgwVUdYb2NwZmZmUHczYUxtRFQxTlhWTHNwOGUKS2oyd1BrVFB2NHpXRHhmMkFuaGlyMmltRHQ1RjdMYmM4RnFOdWhSWThBNnNtcTdQSzMrMW90dXQ1K3hmbTBIdwpPQWxpbTdwUGJTRVZFWGZpTHNhdm5OVVdud0tCZ1FETGN0TVJwM2hvTGNNWGN0MWVOWmJMNUhBRFJ1SmRpQ0g3ClZuRU5FYlBnWDBScnVVNlRVM3VOOFFudVUvZ2gwQXhNaGRuVU5tZDBXM0ZNRjZtMGgyZFN5WWFTb01teEFuYjYKanlnbUtwdk1UazRzUW93dlNqTU1RR01jUlJWaG9kOXFuaVE2YkRKQmN0cjRlRmxqbDB1bUxuNVRlUnArOGFoQwpLYjIrM1hHNUd3S0JnQlBOTzRTNVc3bEV4aXZ1eVpZYWJNSHpjS2NMT0lYUzVRSEpYNm5acXVkMnBHVHlHenkxCnNvbzdTS01GSHZIR3N5dWdYdmxpN1B1Q2d3RVVZdlRSUHVmenQwRnY2clAwMEdtZWFnUEVUclg2Q1BQSEVxZGEKOHU4U2NRRENBbUE4WmVlYlRudXVVOURlWWVmU0dER3kxdys1WjZROXdqVGVaTk9yWFlrSjNQNDVBb0dCQU1FWgpSQUplbktic3dGMnlOUy9rMXpMQXFCeEVIRGhBTEZpOHkrSm1xZjdORFVqZGdobk5ROWtPTGFuYVl3bmN5TCtjCno0cGU5TVI0d2tsQnNGNWJvaEx1bWQ3ejQxc3hockg4VEZRbFh1aUViaWdPSmJZQXpBRFYzL3dHQ2V3MzByRUUKVmtocFJ5M2RrTDRDcEgwbExiVVdMZXFXYURLU3RXdk82SHlPL0JCL0FvR0FFUDRpcTdEVEhwUzNkN2lHeCtaVwpOdGlnMjljQ1R5NWlJbkNYWXVudFpZaW5wSmVPa2g4MUplSmNVTkxZRUNuYTFGaTVxeVB3cnVjZlRDSWluYVFYClJvenV5SmlZMzNvVlA2bmlwYXh5bCtwdlUyQXJpejJCZjhYWTF2b0YvV2JlQjdYdmtJSGRrODJQZlZrdkxUdnMKOG8wa0FEZ05DZlFvRFhnYnJLanVKckU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: code
  name: app
  labels:
    app: app
spec:
  tls:
    - hosts:
        - example.com
      secretName: app
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
